### ISSUE TITLE
YASGUI window should be expandable

### ISSUE THREAD

**Issue by webhart** [materialdigital/ontodocker#3]
Currently the YASGU seems limited to 14 lines. That is to small. It should be possible to flip to fullscreen or similar.

![grafik](https://github.com/user-attachments/assets/b415778d-e22f-4376-96ef-7c4f5acdc990)

**Comment by Lexachoc** [comment]
Are you using dev2 branch? In my side, it seems no issue for dev branch and the YASGUI editor can overflow.

I haven't updated to the latest dev2 commits, below is from dev branch.

![image](https://github.com/user-attachments/assets/42b06c62-ac8e-4f39-bfb9-1ed972e7ed69)

**Comment by JannisGrundmann** [comment]
![ontodockerissue](https://github.com/user-attachments/assets/6dc5baa4-3533-427a-92d5-6a504a360ec0)

I can add linebreaks.
On branch dev2

**Comment by webhart** [comment]
Yes, it can overflow. I meant that the number of visible lines should be increased/increasable. On my screen/resolution I only have 14 visible lines, which I find to little for longer queries.

**Comment by JannisGrundmann** [comment]
![ontodockerissue2](https://github.com/user-attachments/assets/e8514f02-b221-4796-acac-85c228b2d071)

Can you extend the yasgui-window by click&drag the little triangle?

**Comment by webhart** [comment]
Ahh, thank you @JannisGrundmann That is exactly what I need!
